version: '3.4'

services:
  studweb-api:
    image: ${DOCKER_REGISTRY-}studweb
    container_name: studweb-api
    build:
      context: .
      dockerfile: Api/Studweb.Api/Dockerfile
    ports:
      - 5000:80
      - 5001:81
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=5000
      - ASPNETCORE_HTTPS_PORTS=5001
      - ConnectionStrings__Default=Server=mssql,1433;Database=StudwebDB;User=sa;Password=Admin1234!;TrustServerCertificate=True;
    user: root
    depends_on:
      - mssql
    
  mssql:
    container_name: mssql
    image: mcr.microsoft.com/mssql/server:2022-latest
    restart: always
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Admin1234!"
    ports:
      - 1433:1433
    volumes:
      - msdata:/var/opt/mssql
        
  studweb-ui:
    image: ${DOCKER_REGISTRY-}studwebui
    container_name: studweb-ui
    build:
      context: ../../../../Angular/StudwebUI
      dockerfile: Dockerfile
    ports:
      - 4200:80 

volumes:
  msdata: