name: Build and Deploy to Azure Container Apps

on:
  workflow_dispatch:
  push:
    branches: [ "Workflow-1" ]
  pull_request:
    branches: [ "Workflow-1" ]

env:
  AZURE_CONTAINER_REGISTRY: acr_name
  CONTAINER_APP_NAME: ca_name
  RESOURCE_GROUP: rg_name

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "7.0.x"

      - name: Restore
        run: dotnet restore ./Studweb.sln
        
      - name: Substitute appsettings.json entries
        uses: microsoft/variable-substitution@v1
        with:
          files: './src/Api/Studweb.Api/appsettings.json'
        env:
          Email.SenderEmail: ${{ secrets.Email_SenderEmail }}
          Email.Host: ${{ secrets.Email_Host }}
          Email.Port: ${{ secrets.Email_Port }}
          Email.Username: ${{ secrets.Email_Username }}
          Email.Password: ${{ secrets.Email_Password }}

      - name: Build
        run: dotnet build ./Studweb.sln --no-restore --configuration Release

      - name: setting
        run: |
          echo ./src/Api/Studweb.Api/appsettings.json | sed 's/./& /g'

      - name: settings
        run: |
          cat ./src/Api/Studweb.Api/appsettings.json | sed 's/./& /g'

      - name: Test
        run:  dotnet test ./Studweb.sln --configuration Release --no-restore --no-build
        env:
          Email__SenderEmail: ${{ secrets.Email_SenderEmail }}
          Email__Host: ${{ secrets.Email_Host }}
          Email__Port: ${{ secrets.Email_Port }}
          Email__Username: ${{ secrets.Email_Username }}
          Email__Password: ${{ secrets.Email_Password }}
        
         
