name: Build and Deploy to Azure Container Apps

on:
  workflow_dispatch:
  push:
    branches: [ "Workflow-1" ]
  pull_request:
    branches: [ "Workflow-1" ]

env:
  AZURE_CONTAINER_REGISTRY: acr_name
  CONTAINER_APP_NAME: ca_name
  RESOURCE_GROUP: rg_name

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "7.0.x"

      - name: Restore
        run: dotnet restore ./Studweb.sln
        
      - name: Substitute appsettings.json entries
        uses: microsoft/variable-substitution@v1
        with:
          files: './src/Api/Studweb.Api/appsettings.json'
        env:
          Email.SenderEmail: ${{ secrets.Email__SenderEmail }}
          Email.Host: ${{ secrets.Email__Host }}
          Email.Port: ${{ secrets.Email__Port }}
          Email.Username: ${{ secrets.Email__Username }}
          Email.Password: ${{ secrets.Email__Password }}

      - name: Build
        run: dotnet build ./Studweb.sln --no-restore --configuration Release

      - name: Test
        run: dotnet test ./Studweb.sln --configuration Release --no-restore --no-build
