name: Build and Deploy to Azure Container Apps

on:
  workflow_dispatch:
  push:
    branches: [ "Workflow-1" ]
  pull_request:
    branches: [ "Workflow-1" ]

env:
  AZURE_CONTAINER_REGISTRY: acr_name
  CONTAINER_APP_NAME: ca_name
  RESOURCE_GROUP: rg_name

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotne-version: "7.0.x"

      - name: Restore
        run: dotnet restore ./src/Api/Studweb.Api/

      - name: Build
        run: dotnet build ./src/Api/Studweb.Api/ --no-restore --configuration Release

      - name: Test
        run: dotnet test ./Studweb.sln
